language: go

services:
  - docker

before_install:
  - docker build -f test.Dockerfile -t influx6/octo-build ./

env:
  - GIMME_OS=linux GIMME_ARCH=amd64

go:
  - master

install:
  - docker ps -a

script:
  - echo "Done!"
